export const portugalCities = [
    { key: 'lisboa', value: 'Lisboa' },
    { key: 'porto', value: 'Porto' },
    { key: 'braga', value: 'Braga' },
    { key: 'coimbra', value: 'Coimbra' },
    { key: 'leiria', value: 'Leiria' },
    { key: 'setubal', value: 'Setúbal' },
    { key: 'viseu', value: 'Viseu' },
    { key: 'viana-do-castelo', value: 'Viana do Castelo' },
    { key: 'aveiro', value: 'Aveiro' },
    { key: 'faro', value: 'Faro' },
    { key: 'santarem', value: 'Santarém' },
    { key: 'evora', value: 'Évora' },
    { key: 'castelo-branco', value: 'Castelo Branco' },
    { key: 'vila-real', value: 'Vila Real' },
    { key: 'guarda', value: 'Guarda' },
    { key: 'beja', value: 'Beja' },
    { key: 'braganca', value: 'Bragança' },
    { key: 'portalegre', value: 'Portalegre' },
];

export const municipes = {
    aveiro: [
        'Águeda',
        'Albergaria-a-Velha',
        'Anadia',
        'Arouca',
        'Aveiro',
        'Castelo de Paiva',
        'Espinho',
        'Estarreja',
        'Ílhavo',
        'Mealhada',
        'Murtosa',
        'Oliveira de Azeméis',
        'Oliveira do Bairro',
        'Ovar',
        'Santa Maria da Feira',
        'São João da Madeira',
        'Sever do Vouga',
        'Vagos',
        'Vale de Cambra',
    ],
    beja: [
        'Aljustrel',
        'Almodôvar',
        'Alvito',
        'Barrancos',
        'Beja',
        'Castro Verde',
        'Cuba',
        'Ferreira do Alentejo',
        'Mértola',
        'Moura',
        'Odemira',
        'Ourique',
        'Serpa',
        'Vidigueira',
    ],
    braga: [
        'Amares',
        'Barcelos',
        'Braga',
        'Cabeceiras de Basto',
        'Celorico de Basto',
        'Esposende',
        'Fafe',
        'Guimarães',
        'Póvoa de Lanhoso',
        'Terras de Bouro',
        'Vieira do Minho',
        'Vila Nova de Famalicão',
        'Vila Verde',
        'Vizela',
    ],
    braganca: [
        'Alfândega da Fé',
        'Bragança',
        'Carrazeda de Ansiães',
        'Freixo de Espada à Cinta',
        'Macedo de Cavaleiros',
        'Miranda do Douro',
        'Mirandela',
        'Mogadouro',
        'Torre de Moncorvo',
        'Vila Flor',
        'Vimioso',
        'Vinhais',
    ],
    'castelo-branco': [
        'Belmonte',
        'Castelo Branco',
        'Covilhã',
        'Fundão',
        'Idanha-a-nova',
        'Oleiros',
        'Penamacor',
        'Proença-a-nova',
        'Sertã',
        'Vila de Rei',
        'Vila Velha de Ródão',
    ],
    coimbra: [
        'Arganil',
        'Cantanhede',
        'Coimbra',
        'Condeixa-a-Nova',
        'Figueira da Foz',
        'Góis',
        'Lousã',
        'Mira',
        'Miranda do Corvo',
        'Montemor-o-Velho',
        'Oliveira do Hospital',
        'Pampilhosa da Serra',
        'Penacova',
        'Penela',
        'Soure',
        'Tábua',
        'Vila Nova de Poiares',
    ],
    faro: [
        'Albufeira',
        'Alcoutim',
        'Aljezur',
        'Castro Marim',
        'Faro',
        'Lagoa',
        'Lagos',
        'Loulé',
        'Monchique',
        'Olhão',
        'Portimão',
        'São Brás de Alportel',
        'Silves',
        'Tavira',
        'Vila do Bispo',
        'Vila Real de Santo António',
    ],
    guarda: [
        'Aguiar da Beira',
        'Almeida',
        'Celorico da Beira',
        'Figueira de Castelo Rodrigo',
        'Fornos de Algodres',
        'Gouveia',
        'Guarda',
        'Manteigas',
        'Mêda',
        'Pinhel',
        'Sabugal',
        'Seia',
        'Trancoso',
        'Vila Nova de Foz Côa',
    ],
    leiria: [
        'Alcobaça',
        'Alvaiázere',
        'Ansião',
        'Batalha',
        'Bombarral',
        'Caldas da Rainha',
        'Castanheira de Pêra',
        'Figueiró Dos Vinhos',
        'Leiria',
        'Marinha Grande',
        'Nazaré',
        'Óbidos',
        'Pedrógão Grande',
        'Peniche',
        'Pombal',
        'Porto de Mós',
    ],
    lisboa: [
        'Alenquer',
        'Amadora',
        'Arruda Dos Vinhos',
        'Azambuja',
        'Cadaval',
        'Cascais',
        'Lisboa',
        'Loures',
        'Lourinhã',
        'Mafra',
        'Odivelas',
        'Oeiras',
        'Sintra',
        'Sobral de Monte Agraço',
        'Torres Vedras',
        'Vila Franca de Xira',
    ],
    portalegre: [
        'Alter do Chão',
        'Arronches',
        'Avis',
        'Campo Maior',
        'Castelo de Vide',
        'Crato',
        'Elvas',
        'Fronteira',
        'Gavião',
        'Marvão',
        'Monforte',
        'Nisa',
        'Ponte de Sor',
        'Portalegre',
        'Sousel',
    ],
    porto: [
        'Amarante',
        'Baião',
        'Felgueiras',
        'Gondomar',
        'Lousada',
        'Maia',
        'Marco de Canaveses',
        'Matosinhos',
        'Paços de Ferreira',
        'Paredes',
        'Penafiel',
        'Porto',
        'Póvoa de Varzim',
        'Santo Tirso',
        'Trofa',
        'Valongo',
        'Vila do Conde',
        'Vila Nova de Gaia',
    ],
    acores: [
        'Angra do Heroísmo',
        'Calheta de São Jorge',
        'Corvo',
        'Horta',
        'Lagoa (Açores)',
        'Lajes Das Flores',
        'Lajes do Pico',
        'Madalena',
        'Nordeste',
        'Ponta Delgada',
        'Povoação',
        'Praia da Vitória',
        'Ribeira Grande',
        'Santa Cruz da Graciosa',
        'Santa Cruz Das Flores',
        'São Roque do Pico',
        'Velas',
        'Vila do Porto',
        'Vila Franca do Campo',
    ],
    madeira: [
        'Calheta',
        'Câmara de Lobos',
        'Funchal',
        'Machico',
        'Ponta do Sol',
        'Porto Moniz',
        'Porto Santo',
        'Ribeira Brava',
        'Santa Cruz',
        'Santana',
        'São Vicente',
    ],
    santarem: [
        'Abrantes',
        'Alcanena',
        'Almeirim',
        'Alpiarça',
        'Benavente',
        'Cartaxo',
        'Chamusca',
        'Constância',
        'Coruche',
        'Entroncamento',
        'Ferreira do Zêzere',
        'Golegã',
        'Mação',
        'Ourém',
        'Rio Maior',
        'Salvaterra de Magos',
        'Santarém',
        'Sardoal',
        'Tomar',
        'Torres Novas',
        'Vila Nova da Barquinha',
    ],
    setubal: [
        'Alcácer do Sal',
        'Alcochete',
        'Almada',
        'Barreiro',
        'Grândola',
        'Moita',
        'Montijo',
        'Palmela',
        'Santiago do Cacém',
        'Seixal',
        'Sesimbra',
        'Setúbal',
        'Sines',
    ],
    'viana-do-castelo': [
        'Arcos de Valdevez',
        'Caminha',
        'Melgaço',
        'Monção',
        'Paredes de Coura',
        'Ponte da Barca',
        'Ponte de Lima',
        'Valença',
        'Viana do Castelo',
        'Vila Nova de Cerveira',
    ],
    'vila-real': [
        'Alijó',
        'Boticas',
        'Chaves',
        'Mesão Frio',
        'Mondim de Basto',
        'Montalegre',
        'Murça',
        'Peso da Régua',
        'Ribeira de Pena',
        'Sabrosa',
        'Santa Marta de Penaguião',
        'Valpaços',
        'Vila Pouca de Aguiar',
        'Vila Real',
    ],
    viseu: [
        'Alijó',
        'Boticas',
        'Chaves',
        'Mesão Frio',
        'Mondim de Basto',
        'Montalegre',
        'Murça',
        'Peso da Régua',
        'Ribeira de Pena',
        'Sabrosa',
        'Santa Marta de Penaguião',
        'Valpaços',
        'Vila Pouca de Aguiar',
        'Vila Real',
    ],
    evora: [
        'Alandroal',
        'Arraiolos',
        'Borba',
        'Estremoz',
        'Évora',
        'Montemor-o-Novo',
        'Mora',
        'Mourão',
        'Portel',
        'Redondo',
        'Reguengos de Monsaraz',
        'Vendas Novas',
        'Viana do Alentejo',
        'Vila Viçosa',
    ],
};
